### ISSUE TITLE
Aggregation functions that skip missing values

### ISSUE THREAD

**Issue by pkeil7** [JuliaClimate/ClimateBase.jl#65]
Currently, aggregation functions like `mean()` return a missing value, if there is one missing value in the field. However for many applications you would want the missing values to be skipped, e.g. if you only have land surface temperature and have missing values over water. The `skipmissing()` function should be able to do this: https://docs.julialang.org/en/v1/manual/missing/#Skipping-Missing-Values . You could even argue that this should be the default behaviour?

**Comment by Datseris** [comment]
No, this absolutely should not be the default behavior. In software design you want to minimize assumptions you make for the user. The proper mathematical value of the average/median/whatever of an array containing missing values is `missing`, as dictated by `missing`'s logic.

Since a function `skipmissing` exist, they can use it. It isn't a big deal to write the extra 10 characters necessary. Did you try to use it and it didn't work? If so, please report the error message.

BTW, if your array has missing values in the time domain (e.g. some days or months are not covered) then you can consider the function `sinusoidal_continuation` that we offer.

**Comment by pkeil7** [comment]
Well, it doesn't seem to work out of the box: `zonalmean(skipmissing(A))` returns a Methoderror:

`MethodError: no method matching zonalmean(::Base.SkipMissing{ClimArray{Float64, 3, Tuple{Coord{Vector{SVector{2, Float64}}, DimensionalData.CoordMode{Tuple{UnionAll, UnionAll}}, DimensionalData.NoMetadata}, Ti{Vector{Float64}, DimensionalData.Sampled{DimensionalData.Ordered{DimensionalData.ForwardIndex, DimensionalData.ForwardArray, DimensionalData.ForwardRelation}, DimensionalData.Irregular{Tuple{Nothing, Nothing}}, DimensionalData.Points}, Dict{String, String}}, Pre{Vector{Float64}, DimensionalData.Sampled{DimensionalData.Ordered{DimensionalData.ReverseIndex, DimensionalData.ForwardArray, DimensionalData.ForwardRelation}, DimensionalData.Irregular{DimensionalData.AutoBounds}, DimensionalData.Points}, Dict{Any, Any}}}, Tuple{}, Array{Float64, 3}, Dict{String, Any}}})`

I get you point about the proper mathematical value, but this issue arises quite often in climate science I think. Other tools, like cdo and python's xarray therefore also skip missing values by default. So I would argue that in climate science the default assumption is that missing values are skipped.

**Comment by Balinus** [comment]
Without going into the technical detail talked already, my take on this is that missing values are so common in climate sciences that we need something for non finite values. For example, I do not know about an existing weather station that would not have a single missing value in their timeserie. Hence, as soon as we deal with weather station, you would need to add that famous 10 characters each time you are doing statistics. The same apply to climate simulations, but it's more about corner cases, as mentioned in this thread.

So, by experience, I always have an option to ignore missing values. Note that I prefer to have this behaviour set to `false` by default. I want my functions to return a missing/NaN by default and make a conscious effort to add the appropriate flag when needed. Otherwise, you might miss a bug somwehere in your pipeline. For example, imagine you have incorreclty dealt with one of your function and it returns all NaNs except for one finite value: the rest of the pipeline will not properly account for this bug and you might not see it.

What I did in ClimateTools was to use the algorithms in [Images.jl](https://github.com/JuliaImages/Images.jl/blob/master/src/algorithms.jl#L12)

For example, see this function
https://github.com/JuliaImages/Images.jl/blob/a80031eb21662911f7217c6cad7ef0b676002913/src/algorithms.jl#L12

**Comment by Datseris** [comment]
Regardless, I agree that `missing` stuff should be supported more rigorously, but this will need more manpower here. At the moment the possibility of weights that I follow satisfies every single case of missing data. You can modify your array and attribute them the value `0` to every index they have `missing`, and also make statistical weights with `1` where we have non-missig values, and `0` where we have missing. 

But you have to modify the original array nevertheless.
